# test
dist: bionic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.27.0/bazel_0.27.0-linux-x86_64.deb
  - sha256sum -c tools/bazel_0.27.0-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_0.27.0-linux-x86_64.deb

script:
  - bazel test //...

# calls goreleaser
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux